name: Build Android APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential ccache git zip unzip openjdk-17-jdk python3-pip python3-setuptools libffi-dev libssl-dev libxml2-dev libxslt1-dev zlib1g-dev

    - name: Install Buildozer and dependencies
      run: |
        pip install --upgrade pip
        pip install cython==0.29.33 virtualenv
        pip install buildozer

    - name: Accept Android SDK licenses
      run: yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses

    - name: Set up Android SDK
      run: |
        # Install Android SDK if not already installed
        mkdir -p $HOME/android-sdk
        cd $HOME/android-sdk
        wget https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip
        unzip commandlinetools-linux-7583922_latest.zip
        rm commandlinetools-linux-7583922_latest.zip

        # Accept licenses and install required packages
        export ANDROID_HOME=$HOME/android-sdk
        echo "ANDROID_HOME=$ANDROID_HOME" >> $GITHUB_ENV

        yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses
        $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "platform-tools" "build-tools;36.0.0" "platforms;android-30" "extras;google;m2repository" "extras;android;m2repository" "system-images;android-30;google_apis;x86_64"

    - name: Build APK
      run: |
        buildozer android clean
        buildozer android debug


    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: InstaFollowers-APK
        path: bin/*.apk
